name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  review:
    uses: JuiceboxCreative/.github-workflows/.github/workflows/code-review.yml@master
    secrets: inherit
